devguide :
  greeting : "hello default"

---

spring:
  profiles : local
  
devguide :  
  greeting : "hello local"

---

spring:
  profiles : dev
  
devguide :  
  greeting : "hello dev update Test"

---

spring:
  profiles : release
  
devguide :  
  greeting : "hello release"
